<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="C:\Users\2391612\.nuget\packages\nlog.config\4.7.15\contentFiles\any\any\NLog.config" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNetSeleniumExtras.WaitHelpers" Version="3.11.0" />
    <PackageReference Include="ExtentReports" Version="5.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    <PackageReference Include="NLog" Version="5.4.0" />
    <PackageReference Include="NLog.Config" Version="4.7.15" />
    <PackageReference Include="Reqnroll" Version="2.4.0" />
    <PackageReference Include="Reqnroll.NUnit" Version="2.4.0" />
    <PackageReference Include="nunit" Version="4.3.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
    <PackageReference Include="Selenium.Axe" Version="4.0.21" />
    <PackageReference Include="Selenium.Support" Version="4.30.0" />
    <PackageReference Include="Selenium.WebDriver" Version="4.30.0" />
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="134.0.6998.16500" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Screenshots\" />
    <Folder Include="Support\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="pageUrls.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="testConfig.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="nlog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
